# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install system dependencies
    - name: Installing system dependencies
      run: |
        sudo apt update
        sudo apt-get install -y gcc g++ python3-pip libopenjp2-7-dev libgdal-dev gdal-bin libexpat1-dev libgraphicsmagick++1-dev libnetcdf-dev libcppunit-dev doxygen
        pip3 install cget

    # Install dependencies with cget
    - name: Installing dependencies with cget
      run: |
        cd vsm/build
        mv requirements.txt cget_requirements.backup
        $HOME/.local/bin/cget install nlohmann/json -DJSON_BuildTests=Off

    # Run CMake
    - name: Running CMake
      run: |
        cd vsm/build
        cmake ..

    # Build
    - name: Building
      run: |
        cd vsm/build
        make

    # Run tests
    - name: Running tests
      run: |
        cd vsm/build/bin
        ./cm_vsm_test
